// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BituBooking.Infra.Kafka.Contracts.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class HotelCreated : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""HotelCreated"",""namespace"":""BituBooking.Infra.Kafka.Contracts.Events"",""fields"":[{""name"":""Code"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Name"",""type"":""string""},{""name"":""StarsOfCategory"",""type"":""int""},{""name"":""StarsOfRating"",""type"":""int""},{""name"":""Address"",""type"":{""type"":""record"",""name"":""Address"",""namespace"":""BituBooking.Infra.Kafka.Contracts.Events"",""fields"":[{""name"":""Street"",""type"":""string""},{""name"":""District"",""type"":""string""},{""name"":""City"",""type"":""string""},{""name"":""Country"",""type"":""string""},{""name"":""ZipCode"",""type"":""int""}]}},{""name"":""Contacts"",""type"":{""type"":""record"",""name"":""Contacts"",""namespace"":""BituBooking.Infra.Kafka.Contracts.Events"",""fields"":[{""name"":""Mobile"",""type"":""string""},{""name"":""Phone"",""type"":""string""},{""name"":""Email"",""type"":""string""}]}}],""version"":""1""}");
		private System.Guid _Code;
		private string _Name;
		private int _StarsOfCategory;
		private int _StarsOfRating;
		private BituBooking.Infra.Kafka.Contracts.Events.Address _Address;
		private BituBooking.Infra.Kafka.Contracts.Events.Contacts _Contacts;
		public virtual Schema Schema
		{
			get
			{
				return HotelCreated._SCHEMA;
			}
		}
		public System.Guid Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				this._Code = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public int StarsOfCategory
		{
			get
			{
				return this._StarsOfCategory;
			}
			set
			{
				this._StarsOfCategory = value;
			}
		}
		public int StarsOfRating
		{
			get
			{
				return this._StarsOfRating;
			}
			set
			{
				this._StarsOfRating = value;
			}
		}
		public BituBooking.Infra.Kafka.Contracts.Events.Address Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				this._Address = value;
			}
		}
		public BituBooking.Infra.Kafka.Contracts.Events.Contacts Contacts
		{
			get
			{
				return this._Contacts;
			}
			set
			{
				this._Contacts = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Code;
			case 1: return this.Name;
			case 2: return this.StarsOfCategory;
			case 3: return this.StarsOfRating;
			case 4: return this.Address;
			case 5: return this.Contacts;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Code = (System.Guid)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.StarsOfCategory = (System.Int32)fieldValue; break;
			case 3: this.StarsOfRating = (System.Int32)fieldValue; break;
			case 4: this.Address = (BituBooking.Infra.Kafka.Contracts.Events.Address)fieldValue; break;
			case 5: this.Contacts = (BituBooking.Infra.Kafka.Contracts.Events.Contacts)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
