// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BituBooking.Infra.Kafka.Contracts.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class HotelContactsUpdated : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""HotelContactsUpdated"",""namespace"":""BituBooking.Infra.Kafka.Contracts.Events"",""fields"":[{""name"":""HotelCode"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Email"",""type"":""string""},{""name"":""Phone"",""type"":""string""},{""name"":""Mobile"",""type"":""string""}],""version"":""1""}");
		private System.Guid _HotelCode;
		private string _Email;
		private string _Phone;
		private string _Mobile;
		public virtual Schema Schema
		{
			get
			{
				return HotelContactsUpdated._SCHEMA;
			}
		}
		public System.Guid HotelCode
		{
			get
			{
				return this._HotelCode;
			}
			set
			{
				this._HotelCode = value;
			}
		}
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				this._Email = value;
			}
		}
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				this._Phone = value;
			}
		}
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				this._Mobile = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.HotelCode;
			case 1: return this.Email;
			case 2: return this.Phone;
			case 3: return this.Mobile;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.HotelCode = (System.Guid)fieldValue; break;
			case 1: this.Email = (System.String)fieldValue; break;
			case 2: this.Phone = (System.String)fieldValue; break;
			case 3: this.Mobile = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
