// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BituBooking.Infra.Kafka.Contracts.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class RoomAdded : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""RoomAdded"",""namespace"":""BituBooking.Infra.Kafka.Contracts.Events"",""fields"":[{""name"":""Code"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""HotelCode"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Name"",""type"":""string""},{""name"":""Description"",""type"":""string""},{""name"":""PricePerNight"",""type"":""string""},{""name"":""Capacity"",""type"":""int""},{""name"":""AvailableQuantity"",""type"":""int""},{""name"":""Amenities"",""type"":{""type"":""array"",""items"":""string""}}],""version"":""1""}");
		private System.Guid _Code;
		private System.Guid _HotelCode;
		private string _Name;
		private string _Description;
		private string _PricePerNight;
		private int _Capacity;
		private int _AvailableQuantity;
		private IList<System.String> _Amenities;
		public virtual Schema Schema
		{
			get
			{
				return RoomAdded._SCHEMA;
			}
		}
		public System.Guid Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				this._Code = value;
			}
		}
		public System.Guid HotelCode
		{
			get
			{
				return this._HotelCode;
			}
			set
			{
				this._HotelCode = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				this._Description = value;
			}
		}
		public string PricePerNight
		{
			get
			{
				return this._PricePerNight;
			}
			set
			{
				this._PricePerNight = value;
			}
		}
		public int Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				this._Capacity = value;
			}
		}
		public int AvailableQuantity
		{
			get
			{
				return this._AvailableQuantity;
			}
			set
			{
				this._AvailableQuantity = value;
			}
		}
		public IList<System.String> Amenities
		{
			get
			{
				return this._Amenities;
			}
			set
			{
				this._Amenities = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Code;
			case 1: return this.HotelCode;
			case 2: return this.Name;
			case 3: return this.Description;
			case 4: return this.PricePerNight;
			case 5: return this.Capacity;
			case 6: return this.AvailableQuantity;
			case 7: return this.Amenities;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Code = (System.Guid)fieldValue; break;
			case 1: this.HotelCode = (System.Guid)fieldValue; break;
			case 2: this.Name = (System.String)fieldValue; break;
			case 3: this.Description = (System.String)fieldValue; break;
			case 4: this.PricePerNight = (System.String)fieldValue; break;
			case 5: this.Capacity = (System.Int32)fieldValue; break;
			case 6: this.AvailableQuantity = (System.Int32)fieldValue; break;
			case 7: this.Amenities = (IList<System.String>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
